name: CI GitHubActions

# When to trigger the workflow: on push or pull request to the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # server Linux GitHub Actions
    runs-on: ubuntu-latest

    steps:
      # downloading code
      - uses: actions/checkout@v4

      # installing Java 21
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # using Gradle Wrapper
      - uses: gradle/actions/setup-gradle@v4

      # making gradlew executable
      - run: chmod +x gradlew

      # throwing error if build fails
      - run: ./gradlew build
